# Use root/example as user/password credentials
version: '4.4'

services:

  firefox:
    image: selenium/standalone-firefox:4.1.2-20220217
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    hostname: firefox

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["--auth"]
    depends_on:
      - firefox

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo

  sync-robot-api:
    build: ./api
    restart: always
    ports:
      - 4000:4000
    environment:
      SELENIUM_HOST: firefox
      SELENIUM_PORT: 4444
    depends_on:
      - mongo-express
    command: ["node","."]

  sync-robot-ui:
    build: ./ui
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - sync-robot-api
    command: ["node","."]