if (db.district_team_season_name_mapping.find().count() === 0) {
  db.district_team_season_name_mapping.insertMany([
    {"district":"district_1","districtSystemTeamName":"Bessie Carmichael Juniors 2021-2022","teamSeasonName":"Bessie Carmichael Juniors-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Bessie Carmichael Select 2021-2022","teamSeasonName":"Bessie Carmichael Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Bret Harte Juniors 2021-2022","teamSeasonName":"Bret Harte Juniors-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Bret Harte Select 2021-2022","teamSeasonName":"Bret Harte Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Bryant Select 2021-2022","teamSeasonName":"Bryant Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Cleveland Select 2021-2022","teamSeasonName":"Cleveland Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"ER Taylor Juniors 2021-2022","teamSeasonName":"ER Taylor Juniors-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"ER Taylor Select 2021-2022","teamSeasonName":"ER Taylor Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Everett 2021-2022","teamSeasonName":"Everett Middle School-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Francisco Middle School 2021-2022","teamSeasonName":"Francisco Boys-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Hillcrest Juniors 2021-2022","teamSeasonName":"Hillcrest Juniors-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Hillcrest Select 2021-2022","teamSeasonName":"Bessie Carmichael Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"IHDC Select 2021-2022","teamSeasonName":"IHDC Select-2021 Fall"},

    {"district":"district_1","districtSystemTeamName":"John Muir 2021-2022","teamSeasonName":"John Muir-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Joseph Lee Rec Center 2021-2022","teamSeasonName":"Joseph Lee Rec Center-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"MLK Coed 2021-2022","teamSeasonName":"MLK Coed-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Paul Revere Juniors 2021-2022","teamSeasonName":"Paul Revere Juniors-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Paul Revere Middle 2021-2022","teamSeasonName":"Paul Revere Middle-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Paul Revere Select 2021-2022","teamSeasonName":"Paul Revere Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Salvation Army KROC 2021-2022","teamSeasonName":"Salvation Army KROC-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Sanchez Juniors 2021-2022","teamSeasonName":"Sanchez Juniors-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Sanchez Select 2021-2022","teamSeasonName":"Sanchez Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"TECA - Program Site Juniors 2021-2022","teamSeasonName":"TECA Juniors"},
    {"district":"district_1","districtSystemTeamName":"TECA - Program Site Select 2021-2022","teamSeasonName":"TECA SELECT-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"TECA MS Boys 2021-2022","teamSeasonName":"TECA MS Boys-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Up on Top 2021-2022","teamSeasonName":"Up on Top - Program Site Select-2021 Fall"},
    {"district":"district_1","districtSystemTeamName":"Bessie Carmichael Juniors 2021-2022","teamSeasonName":"Bessie Carmichael Juniors-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Bessie Carmichael Select 2021-2022","teamSeasonName":"Bessie Carmichael Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Bret Harte Juniors 2021-2022","teamSeasonName":"Bret Harte Juniors-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Bret Harte Select 2021-2022","teamSeasonName":"Bret Harte Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Bryant Select 2021-2022","teamSeasonName":"Bryant Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Cleveland Select 2021-2022","teamSeasonName":"Cleveland Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"ER Taylor Juniors 2021-2022","teamSeasonName":"ER Taylor Juniors-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"ER Taylor Select 2021-2022","teamSeasonName":"ER Taylor Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Hillcrest Select 2021-2022","teamSeasonName":"Hillcrest Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"IHDC Select 2021-2022","teamSeasonName":"IHDC Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"John Muir 2021-2022","teamSeasonName":"John Muir-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"MLK Coed 2021-2022","teamSeasonName":"MLK Coed-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Paul Revere Juniors 2021-2022","teamSeasonName":"Paul Revere Juniors-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Paul Revere Middle 2021-2022","teamSeasonName":"Paul Revere Middle-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Paul Revere Select 2021-2022","teamSeasonName":"Paul Revere Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Salvation Army KROC 2021-2022","teamSeasonName":"Salvation Army KROC-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Sanchez Select 2021-2022","teamSeasonName":"Sanchez Select-2022 Spring"},
    {"district":"district_1","districtSystemTeamName":"Up on Top 2021-2022","teamSeasonName":"Up on Top - Program Site Select-2022 Spring"}
  ]);
}